name: Code formatting checks
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  python-black:
    name: Format code with Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run black formatter checks
        uses: psf/black@stable
        with:
          src: "./"
          options: "--check --diff --color"
          jupyter: true
  
  python-isort:
    name: Fomat code with isort
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run isort formatter checks
        uses: isort/isort-action@v1.0.0
        with:
          configuration: "--check --diff --color"
          requirementsFiles: "requirements.txt"
