name: A workflow for my Hello world file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # use our custom created action
      - uses: ./my-custom-action
        with:
          MY_NAME: "Mona"
