# The name of the workflow (or "action") that will be displayed on the repo's
#   actions page
name: Python master push-pull action

# What change, within this Github repo, is going to cause this action to happen.
# For example, here any "push" or "pull request" on the "master" branch will
#   cause this action to be performed.
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# List of jobs that run as part of this workflow. Each job run independently of the
#   the others and in it's own virtual environment.
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:
  build:
    # The type of machine to run this job on.
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    # "strategy.matrix" basically allows you to change one piece of your action while keeping the rest
    #   the same. In this example, we're changing the version of Python a few times to verify it works
    #     with past versions, but everything else in the action stays the same across tests.
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      matrix:
        python-version:
          - 3.5
          - 3.6
          - 3.7
          - 3.8
    # "steps" defines the actual testing steps that will be performed.
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
      # This is an action provided by GitHub that will check out your repository onto the runner, so that it can be built and tested.
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses
      - uses: actions/checkout@v2
      # Give this step a "name" by substituting the variable: ${{ matrix.python-version }}
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsname
      - name: Set up Python ${{ matrix.python-version }}
        # Using another Github-provided action to setup a Python environment within the runner that is performing this test.
        uses: actions/setup-python@v2
        # Specify the version of Python we want to use
        with:
          python-version: ${{ matrix.python-version }}
      # Another name section
      - name: "Install dependencies"
        # Steps for the runner to run
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun
        run: |
          # Update "pip" to the newest version
          python -m pip install --upgrade pip

          # Install flake8 and pytest
          pip install flake8 pytest

          # If there is a "requirements.txt" file, then install everything from it, otherwise do nothing else.
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Another naming section
      - name: Lint with flake8
        # Here we're running the flake8 specific steps to lint our program.
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      # The last name section.
      - name: Test with pytest
        # Finally, run the actual pytest tests.
        run: pytest -v
